DROP TABLE LOC_AGENCIA_BANCO CASCADE CONSTRAINTS;

DROP TABLE LOC_ENDERECO_PROPRIETARIO CASCADE CONSTRAINTS;

DROP TABLE LOC_ENDERECO_CLIENTE CASCADE CONSTRAINTS;

DROP TABLE LOC_MOVTO_COMISSAO CASCADE CONSTRAINTS;

DROP TABLE LOC_MOVTO_COBRANCA CASCADE CONSTRAINTS;

DROP TABLE LOC_DUPLICATA CASCADE CONSTRAINTS;

DROP TABLE LOC_NF_LOCACAO_ITEM CASCADE CONSTRAINTS;

DROP TABLE LOC_NF_LOCACAO CASCADE CONSTRAINTS;

DROP TABLE LOC_CFO CASCADE CONSTRAINTS;

DROP TABLE LOC_COND_PARCELAS CASCADE CONSTRAINTS;

DROP TABLE LOC_COND_PAGTO CASCADE CONSTRAINTS;

DROP TABLE LOC_RESERVA CASCADE CONSTRAINTS;

DROP TABLE LOC_ITEM_LOCACAO CASCADE CONSTRAINTS;

DROP TABLE LOC_PEDIDO_LOCACAO CASCADE CONSTRAINTS;

DROP TABLE LOC_AGENCIA CASCADE CONSTRAINTS;

DROP TABLE LOC_IMPOSTOS CASCADE CONSTRAINTS;

DROP TABLE LOC_CIDADE CASCADE CONSTRAINTS;

DROP TABLE LOC_OPERADORA_DDD CASCADE CONSTRAINTS;

DROP TABLE LOC_DDD_PREFIXO CASCADE CONSTRAINTS;

DROP TABLE LOC_DDD CASCADE CONSTRAINTS;

DROP TABLE LOC_PREFIXO CASCADE CONSTRAINTS;

DROP TABLE LOC_OPERADORA CASCADE CONSTRAINTS;

DROP TABLE LOC_FUNCIONARIO CASCADE CONSTRAINTS;

DROP TABLE LOC_DEPTO CASCADE CONSTRAINTS;

DROP TABLE LOC_CLASSE CASCADE CONSTRAINTS;

DROP TABLE LOC_CLIENTE CASCADE CONSTRAINTS;

DROP TABLE LOC_FOTOS_VEICULO CASCADE CONSTRAINTS;

DROP TABLE LOC_VEICULO CASCADE CONSTRAINTS;

DROP TABLE LOC_GRUPO CASCADE CONSTRAINTS;

DROP TABLE LOC_PROPRIETARIO CASCADE CONSTRAINTS;

DROP TABLE LOC_MOVTO_TRANSACAO CASCADE CONSTRAINTS;

DROP TABLE LOC_ESTADO CASCADE CONSTRAINTS;

DROP TABLE LOC_CLI_FISICA CASCADE CONSTRAINTS;

DROP TABLE LOC_CLI_JURIDICA CASCADE CONSTRAINTS;

DROP TABLE LOC_OPERADORA_CARTAO CASCADE CONSTRAINTS;

DROP TABLE LOC_BANCO CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_LOC_MOVTO_TRANSACAO;

DROP SEQUENCE SEQ_LOC_DDD;

DROP SEQUENCE SEQ_LOC_CLI;

DROP SEQUENCE SEQ_LOC_PEDIDO_LOCACAO;