CREATE TABLE LOC_BANCO (
       CD_BANCO             NUMBER(4) 		NOT NULL,
       NM_BANCO             VARCHAR2(80) 	NOT NULL,
	   URL                  VARCHAR2(50)
);

ALTER TABLE LOC_BANCO
       ADD CONSTRAINT PK_BANCO PRIMARY KEY (CD_BANCO);

CREATE TABLE LOC_AGENCIA_BANCO (
       CD_AGENCIA           NUMBER(8) 		NOT NULL,
       END_AGENCIA          VARCHAR2(30) 	NOT NULL,
       CEP                  NUMBER(8) 		NOT NULL,
       NUMERO               NUMBER(4) 		NOT NULL,
       APELIDO              VARCHAR2(30) 	NULL,
       CD_BANCO             NUMBER(4) 		NOT NULL
);

ALTER TABLE LOC_AGENCIA_BANCO
       ADD CONSTRAINT PK_LOC_AGENCIA_BANCO PRIMARY KEY (CD_AGENCIA, CD_BANCO);

CREATE TABLE LOC_CFO (
       CFOP                 NUMBER(4) 		NOT NULL,
       DESC_CFO             VARCHAR2(400) 	NOT NULL,
       APLICACAO            VARCHAR2(2000) 	NULL
);

ALTER TABLE LOC_CFO
       ADD CONSTRAINT PK_LOC_CFO PRIMARY KEY (CFOP);

CREATE TABLE LOC_CIDADE (
       CD_CIDADE            NUMBER(8) 		NOT NULL,
       NM_CIDADE            VARCHAR2(40) 	NOT NULL,
       CD_ESTADO            VARCHAR2(2) 	NOT NULL
);

ALTER TABLE LOC_CIDADE
       ADD CONSTRAINT PK_LOC_CIDADE PRIMARY KEY (CD_CIDADE, CD_ESTADO);

CREATE TABLE LOC_AGENCIA (
       CD_CIDADE            NUMBER(8) 		NOT NULL,
       CD_AGENCIA           NUMBER(8) 		NOT NULL,
       NM_LOGRADOURO        VARCHAR2(40) 	NOT NULL,
       NM_BAIRRO            VARCHAR2(30) 	NOT NULL,
       NUMERO               NUMBER(4) 		NOT NULL,
       CD_ESTADO            VARCHAR2(2) 	NOT NULL
);

ALTER TABLE LOC_AGENCIA
       ADD  CONSTRAINT PK_LOC_AGENCIA PRIMARY KEY (CD_CIDADE, CD_AGENCIA, CD_ESTADO);

CREATE TABLE LOC_CLI_FISICA (
       CD_CLIENTE           NUMBER(8) 		NOT NULL,
       NR_CPF               NUMBER(12) 		NOT NULL,
       NR_HABILITACAO       NUMBER(18) 		NULL,
       DT_NASCIMENTO        DATE 			NULL,
       NR_RG                NUMBER(10) 		NOT NULL,
       TIT_ELEITOR          NUMBER(15) 		
);

ALTER TABLE LOC_CLI_FISICA
       ADD CONSTRAINT PK_LOC_CLI_FISICA PRIMARY KEY (CD_CLIENTE);

CREATE TABLE LOC_CLI_JURIDICA (
       CD_CLIENTE           NUMBER(8) 		NOT NULL,
       NR_CNPJ              NUMBER(14) 		NOT NULL,
       INS_ESTADUAL         NUMBER(18) 		NULL,
       DT_FUNDACAO          DATE 		NULL,
       INS_MUNICIPAL        NUMBER(15) 		NOT NULL,
       NM_FANTASIA          VARCHAR2(20) 	NOT NULL
);

ALTER TABLE LOC_CLI_JURIDICA
       ADD CONSTRAINT PK_LOC_CLI_JURIDICA PRIMARY KEY (CD_CLIENTE);

CREATE TABLE LOC_CLIENTE (
       CD_CLIENTE           NUMBER(8) 		NOT NULL,
	   NM_CLIENTE           VARCHAR2(50)    NOT NULL,
       TP_CLIENTE           VARCHAR2(1) 	NOT NULL,
       NR_ESTRELAS          NUMBER(2) 		NULL,
       TELEFONE             VARCHAR2(15) 	NULL,
       FAX                  VARCHAR2(15) 	NULL,
	   NR_HABILITACAO       NUMBER(12)      NULL
);

ALTER TABLE LOC_CLIENTE
       ADD CONSTRAINT PK_LOC_CLIENTE PRIMARY KEY (CD_CLIENTE);

ALTER TABLE LOC_CLIENTE
       ADD CONSTRAINT CK_TP_CLIENTE CHECK (TP_CLIENTE IN ('F','J'));

	   
CREATE TABLE LOC_COND_PAGTO (
       CD_CONDICAO          NUMBER(8) 		NOT NULL,
       DESC_CONDICAO        VARCHAR2(30) 	NOT NULL
);

ALTER TABLE LOC_COND_PAGTO
       ADD CONSTRAINT PK_LOC_COND_PAGTO PRIMARY KEY (CD_CONDICAO);

CREATE TABLE LOC_COND_PARCELAS (
       CD_CONDICAO          NUMBER(8) 		NOT NULL,
       CD_PARCELA           NUMBER(8) 		NOT NULL,
       DESC_COND_PARC       VARCHAR2(40) 	NOT NULL,
       QTD_DIAS             NUMBER(4) 		NOT NULL
);

ALTER TABLE LOC_COND_PARCELAS
       ADD CONSTRAINT PK_LOC_COND_PARCELAS PRIMARY KEY (CD_CONDICAO, CD_PARCELA);


CREATE TABLE LOC_DDD (
       CD_DDD               NUMBER(3) 		NOT NULL,
	   SEQ_DDD              NUMBER(5)       NOT NULL,   
	   ESTADO_DDD           VARCHAR2(2)     NOT NULL,
       CIDADE_DDD           VARCHAR2(40) 	NOT NULL
);

ALTER TABLE LOC_DDD
       ADD CONSTRAINT PK_LOC_DDD PRIMARY KEY (CD_DDD, SEQ_DDD, ESTADO_DDD);

CREATE TABLE LOC_DDD_PREFIXO (
       CD_PREFIXO           NUMBER(4) 		NOT NULL,
       CD_DDD               NUMBER(3) 		NOT NULL,
	   SEQ_DDD              NUMBER(5)       NOT NULL,
	   ESTADO_DDD           VARCHAR2(2)     NOT NULL
);

ALTER TABLE LOC_DDD_PREFIXO
       ADD CONSTRAINT PK_LOC_DDD_PREFIXO PRIMARY KEY (CD_PREFIXO, CD_DDD, SEQ_DDD, ESTADO_DDD);

CREATE TABLE LOC_DEPTO (
       CD_DEPTO             NUMBER(5) 		NOT NULL,
       NM_DEPTO             VARCHAR(40) 	NULL,
	   VL_ORCAMENTO         NUMBER(10,2)    NULL
);

ALTER TABLE LOC_DEPTO
       ADD CONSTRAINT PK_LOC_DEPTO PRIMARY KEY (CD_DEPTO);
	   
CREATE TABLE LOC_CLASSE (
       CD_CLASSE            NUMBER(5) 		NOT NULL,
       NM_CLASSE            VARCHAR(40) 	NOT NULL
);

ALTER TABLE LOC_CLASSE
       ADD CONSTRAINT PK_LOC_CLASSE PRIMARY KEY (CD_CLASSE);	   

CREATE TABLE LOC_DUPLICATA (
       NR_NOTA              NUMBER(6) 		NOT NULL,
       CD_DUPLICATA         NUMBER(8) 		NOT NULL,
       VL_DUPLICATA         NUMBER(10,2) 	NOT NULL,
       DT_VENCTO            DATE 			NOT NULL,
       DT_PAGTO             DATE 			NULL,
       PERC_DESCTO          NUMBER(2) 		NOT NULL,
       DT_PAGTO_DESCTO      DATE 			NOT NULL,
       VL_DESCTO            NUMBER(10,2) 	NOT NULL,
       NR_DIAS_ATRASO       NUMBER(3) 		NULL,
       SITUACAO             VARCHAR2(1) DEFAULT 'A' NOT NULL
);

ALTER TABLE LOC_DUPLICATA
       ADD CONSTRAINT PK_LOC_DUPLICATA PRIMARY KEY (NR_NOTA, CD_DUPLICATA);

ALTER TABLE LOC_DUPLICATA
       ADD CONSTRAINT CK_SITUACAO CHECK (SITUACAO IN ('A', 'C', 'L'));

CREATE TABLE LOC_ENDERECO_CLIENTE (
       CD_END_CLI           NUMBER(5) 		NOT NULL,
       LOGRADOURO           VARCHAR2(60) 	NOT NULL,
       BAIRRO               VARCHAR2(40) 	NOT NULL,
       CEP                  NUMBER(8) 		NOT NULL,
       TP_ENDERECO          VARCHAR2(1) 	NOT NULL,
       CD_CLIENTE           NUMBER(8) 		NOT NULL,
       CD_CIDADE            NUMBER(8) 		NULL,
       CD_ESTADO            VARCHAR2(2) 	NULL,
       NUMERO               NUMBER(8) 		NULL,
       COMPLEMENTO          VARCHAR2(50) 	NULL
);

ALTER TABLE LOC_ENDERECO_CLIENTE
       ADD CONSTRAINT PK_LOC_ENDERECO_CLIENTE PRIMARY KEY (CD_END_CLI, CD_CLIENTE);

ALTER TABLE LOC_ENDERECO_CLIENTE
       ADD CONSTRAINT CK_TP_ENDERECO_CLIENTE CHECK (TP_ENDERECO IN ('C', 'R', 'E'));

CREATE TABLE LOC_ENDERECO_PROPRIETARIO (
       CD_ENDERECO_PROP     NUMBER(3) 		NOT NULL,
       LOGRADOURO           VARCHAR2(60) 	NOT NULL,
       CD_PROPRIETARIO      NUMBER(10) 		NOT NULL,
       CEP                  NUMBER(8) 		NOT NULL,
       BAIRRO               VARCHAR2(40) 	NOT NULL,
       TP_ENDERECO          VARCHAR2(1) 	NOT NULL,
       CD_CIDADE            NUMBER(8) 		NULL,
       COMPLEMENTO          VARCHAR2(60) 	NULL,
       CD_ESTADO            VARCHAR2(2) 	NULL
);

ALTER TABLE LOC_ENDERECO_PROPRIETARIO
       ADD CONSTRAINT PK_LOC_ENDERECO_PROPRIETARIO PRIMARY KEY (CD_ENDERECO_PROP, CD_PROPRIETARIO);

ALTER TABLE LOC_ENDERECO_PROPRIETARIO
       ADD CONSTRAINT CK_TP_ENDERECO_PROPRIETARIO CHECK (TP_ENDERECO IN ('C', 'R'));

CREATE TABLE LOC_ESTADO (
       CD_ESTADO            VARCHAR2(2) 	NOT NULL,
       NM_ESTADO            VARCHAR2(30) 		NULL
);

ALTER TABLE LOC_ESTADO
       ADD CONSTRAINT LOC_ESTADO PRIMARY KEY (CD_ESTADO);

CREATE TABLE LOC_FOTOS_VEICULO (
       NR_PLACA             VARCHAR2(7) 	NOT NULL,
       NR_FOTO              NUMBER(3) 		NOT NULL,
       FOTO                 BLOB 			NULL
);

ALTER TABLE LOC_FOTOS_VEICULO
       ADD CONSTRAINT PK_LOC_FOTOS_VEICULO PRIMARY KEY (NR_PLACA, NR_FOTO);

CREATE TABLE LOC_FUNCIONARIO (
       CD_FUNC              NUMBER(5) 		NOT NULL,
       NM_FUNC              VARCHAR2(40) 	NULL,
       DT_INICIO            DATE 		NULL,
       CD_GERENTE           NUMBER(5) 		NULL,
       NR_CPF               NUMBER(12) 		NULL,
       VL_SALARIO           NUMBER(11,2) 	NULL,
       VL_PERC_COMISSAO     NUMBER(11,2) 	NULL,
       CD_DEPTO             NUMBER(5) 		NOT NULL,
       NR_ESTRELAS          NUMBER(1)           NULL,
	   CD_CLASSE            NUMBER(5) 		NULL,
       CARGO                VARCHAR2(40)    NULL
);

ALTER TABLE LOC_FUNCIONARIO
       ADD CONSTRAINT PK_LOC_FUNCIONARIO PRIMARY KEY (CD_FUNC);

CREATE TABLE LOC_GRUPO (
       CD_GRUPO             NUMBER(3) 		NOT NULL,
       DS_GRUPO             VARCHAR2(100) 	NOT NULL,
       VL_LOCACAO_DIARIA    NUMBER(8,2) 	NULL
);

ALTER TABLE LOC_GRUPO
       ADD CONSTRAINT PK_LOC_GRUPO PRIMARY KEY (CD_GRUPO);

CREATE TABLE LOC_IMPOSTOS (
       CD_IMPOSTO           VARCHAR2(4) 	NOT NULL,
       DT_INI_VIGENCIA      DATE 			NOT NULL,
       DT_FIN_VIGENCIA      DATE 			NULL,
       ALIQUOTA             NUMBER(2,2) 	NOT NULL,
       CD_CIDADE            NUMBER(8) 		NULL,
       CD_ESTADO            VARCHAR2(2) 	NULL
);

ALTER TABLE LOC_IMPOSTOS
       ADD CONSTRAINT PK_LOC_IMPOSTOS PRIMARY KEY (CD_IMPOSTO, DT_INI_VIGENCIA);

CREATE TABLE LOC_ITEM_LOCACAO (
       DT_RETIRADA          DATE 			NULL,
       NR_ITEM              NUMBER(5) 		NOT NULL,
       DT_ENTREGA           DATE 			NULL,
       QT_DIAS              NUMBER(3) 		NULL,
       VL_LOCACAO           NUMBER(11,2) 	NULL,
       NR_PLACA             VARCHAR2(7) 	NOT NULL,
       VL_TOTAL             NUMBER(11,2) 	NULL,
       NR_PEDIDO            NUMBER(8) 		NOT NULL
);

ALTER TABLE LOC_ITEM_LOCACAO
       ADD CONSTRAINT PK_LOC_ITEM_LOCACAO PRIMARY KEY (NR_PEDIDO, NR_ITEM);

create index idx_iloc1 on loc_item_locacao(dt_retirada);
create index idx_iloc2 on loc_item_locacao(dt_entrega);
create index idx_iloc3 on loc_item_locacao(qt_dias);
create index idx_iloc4 on loc_item_locacao(vl_locacao);
create index idx_iloc5 on loc_item_locacao(vl_total);


CREATE TABLE LOC_MOVTO_COBRANCA (
       CD_MOVTO             NUMBER(8) 		NOT NULL,
       DT_MVTO              DATE 			NOT NULL,
       VL_MOVTO             NUMBER(12,2) 	NOT NULL,
       DT_PAGTO             DATE 			NULL,
       NR_NOTA              NUMBER(6) 		NOT NULL,
       CD_DUPLICATA         NUMBER(8) 		NOT NULL,
       DEB_CRED             VARCHAR2(1) 	NOT NULL,
       CD_TRANSACAO         NUMBER(8) 		NOT NULL,
       TP_PAGTO             VARCHAR2(2) 	NOT NULL,
       NR_DOCTO_PAGTO       NUMBER(15) 		NULL,
       CD_OPERADORA         NUMBER(8) 		NULL,
       CD_BANCO             NUMBER(4) 		NULL
);

ALTER TABLE LOC_MOVTO_COBRANCA
       ADD CONSTRAINT PK_LOC_MOVTO_COBRANCA PRIMARY KEY (CD_MOVTO, NR_NOTA, CD_DUPLICATA);

ALTER TABLE LOC_MOVTO_COBRANCA
       ADD CONSTRAINT CK_DEB_CRED CHECK (DEB_CRED IN ('D', 'C'));

ALTER TABLE LOC_MOVTO_COBRANCA
       ADD CONSTRAINT CK_TP_PAGTO CHECK (TP_PAGTO IN ('BB', 'CH', 'DI', 'DC', 'NP',  'CC'));

CREATE TABLE LOC_MOVTO_COMISSAO (
       CD_MOVTO_COB         NUMBER(8) 		NOT NULL,
       CD_MOVTO             NUMBER(8) 		NOT NULL,
       NR_NOTA              NUMBER(6) 		NOT NULL,
       CD_DUPLICATA         NUMBER(8) 		NOT NULL,
       DEB_CRED             VARCHAR2(1) 	NOT NULL,
       CD_FUNC              NUMBER(5) 		NOT NULL,
       VL_COMISSAO          NUMBER(10,2) 	NOT NULL,
       PERC_COMISSAO        NUMBER(10,2) 	NOT NULL
);

ALTER TABLE LOC_MOVTO_COMISSAO
       ADD CONSTRAINT PK_LOC_MOVTO_COMISSAO PRIMARY KEY (CD_MOVTO_COB);

ALTER TABLE LOC_MOVTO_COMISSAO
       ADD CONSTRAINT CK_DEB_CRED_MOVTO_COMISSAO CHECK (DEB_CRED IN ('D', 'C'));

CREATE TABLE LOC_MOVTO_TRANSACAO (
       CD_TRANSACAO         NUMBER(8) 		NOT NULL,
       DESC_TRANSACAO       VARCHAR2(30) 	NOT NULL,
       DEB_CRED             VARCHAR2(1) 	NOT NULL
                                   CHECK (DEB_CRED IN ('D', 'C')),
       STATUS_TRANSACAO     VARCHAR2(1) 	NOT NULL
                                   CHECK (STATUS_TRANSACAO IN ('A','I'))
);

ALTER TABLE LOC_MOVTO_TRANSACAO
       ADD CONSTRAINT PK_LOC_MOVTO_TRANSACAO PRIMARY KEY (CD_TRANSACAO);

ALTER TABLE LOC_MOVTO_TRANSACAO
       ADD CONSTRAINT CK_DEB_CRED_MOVTO_TRANSACAO CHECK (DEB_CRED IN ('D', 'C'));
	   
	   
CREATE TABLE LOC_NF_LOCACAO (
       NR_NOTA              NUMBER(6) 		NOT NULL,
       NR_PEDIDO            NUMBER(8) 		NOT NULL,
       ENDERECO             VARCHAR2(40) 	NOT NULL,
       BAIRRO               VARCHAR2(40) 	NOT NULL,
       CIDADE               VARCHAR2(40) 	NOT NULL,
       ESTADO               VARCHAR2(2) 	NOT NULL,
       CEP                  NUMBER(8) 		NOT NULL,
       VL_TOTAL_NF          NUMBER(12,2) 	NULL,
       CD_CONDICAO          NUMBER(8) 		NOT NULL,
       DT_EMISSAO           DATE 			NOT NULL,
       DT_SAIDA             DATE 			NULL,
       CFOP                 NUMBER(4) 		NOT NULL
);


ALTER TABLE LOC_NF_LOCACAO
       ADD CONSTRAINT PK_LOC_NF_LOCACAO PRIMARY KEY (NR_NOTA);


CREATE TABLE LOC_NF_LOCACAO_ITEM (
       NR_NOTA              NUMBER(6) 		NOT NULL,
       NR_PLACA             VARCHAR2(7) 	NOT NULL,
       VL_UNITARIO          NUMBER(10,2) 	NOT NULL,
       DESC_PRODUTO         VARCHAR2(45)	NOT NULL,
       QUANTIDADE           NUMBER(3) 		NOT NULL,
       VL_TOTAL             NUMBER(10,2) 	NOT NULL,
       ALIQ_ICMS            NUMBER(2) 		NULL
);


ALTER TABLE LOC_NF_LOCACAO_ITEM
       ADD CONSTRAINT PK_LOC_NF_LOCACAO_ITAM PRIMARY KEY (NR_NOTA, NR_PLACA);


CREATE TABLE LOC_OPERADORA (
       CD_OPERADORA         NUMBER(4) 		NOT NULL,
       NM_OPERADORA         VARCHAR2(40) 	NOT NULL
);

ALTER TABLE LOC_OPERADORA
       ADD CONSTRAINT PK_LOC_OPERADORA PRIMARY KEY (CD_OPERADORA);


CREATE TABLE LOC_OPERADORA_CARTAO (
       CD_OPERADORA         NUMBER(8) 		NOT NULL,
       NM_OPERADORA         VARCHAR2(50) 	NOT NULL
);

ALTER TABLE LOC_OPERADORA_CARTAO
       ADD CONSTRAINT PK_LOC_OPERADORA_CARTAO PRIMARY KEY (CD_OPERADORA);


CREATE TABLE LOC_OPERADORA_DDD (
       CD_OPERADORA         NUMBER(4) 		NOT NULL,
       CD_DDD               NUMBER(3) 		NOT NULL,
       SEQ_DDD              NUMBER(5) 		NOT NULL,
       ESTADO_DDD           VARCHAR2(2) 	NOT NULL
);

ALTER TABLE LOC_OPERADORA_DDD
       ADD  CONSTRAINT PK_LOC_OPERADORA_DDD PRIMARY KEY (CD_OPERADORA, cd_ddd, SEQ_DDD, ESTADO_DDD);

	   
CREATE TABLE LOC_PEDIDO_LOCACAO (
       CD_CLIENTE           NUMBER(8) 		NOT NULL,
       NR_PEDIDO            NUMBER(8) 		NOT NULL,
       DT_LOCACAO           DATE 		NOT NULL,
       QT_DIAS              NUMBER(5) 		NULL,
       VL_TOTAL             NUMBER(10,2) 	NULL,
       STATUS               VARCHAR2(2) 	NULL,
       TP_PAGTO             VARCHAR2(2) 	NULL,
       DT_RETIRADA          DATE 		NULL,
       DT_ENTREGA           DATE 		NULL,
       CD_FUNC              NUMBER(5) 		NULL,
       CD_CIDADE            NUMBER(8) 		NULL,
       CD_AGENCIA           NUMBER(8) 		NULL,
       CD_ESTADO            VARCHAR2(2) 	NULL
);

ALTER TABLE LOC_PEDIDO_LOCACAO
       ADD CONSTRAINT PK_LOC_PEDIDO_LOCACAO PRIMARY KEY (NR_PEDIDO);

ALTER TABLE loc_pedido_locacao 
       ADD constraint fk_estado_plocacao FOREIGN KEY (cd_estado) 
           REFERENCES loc_estado(cd_estado);

ALTER TABLE LOC_PEDIDO_LOCACAO
       ADD CONSTRAINT CK_STATUS CHECK (STATUS IN ('PG', 'AB', 'CC','IN'));

ALTER TABLE LOC_PEDIDO_LOCACAO
       ADD CONSTRAINT CK_TP_PAGTO_LOCACAO CHECK (TP_PAGTO IN ('BB', 'CH', 'DI', 'DC', 'NP',  'CC'));

	   
CREATE TABLE LOC_PREFIXO (
       CD_PREFIXO           NUMBER(8) 		NOT NULL,
       DESC_PREFIXO         VARCHAR2(30) 	NOT NULL
);

ALTER TABLE LOC_PREFIXO
       ADD CONSTRAINT PK_LOC_PREFIXO PRIMARY KEY (CD_PREFIXO);

CREATE TABLE LOC_PROPRIETARIO (
       CD_PROPRIETARIO      NUMBER(10) 		NOT NULL,
       NOME_PROPRIETARIO    VARCHAR2(50) 	NOT NULL,
       TP_PROPRIETARIO      VARCHAR2(1) 	NULL,
       TELEFONE             VARCHAR2(25) 	NULL,
       NR_CPF               NUMBER(12) 		NULL,
       NR_CGC               NUMBER(15) 		NULL,
       DS_EMAIL		    VARCHAR2(80)	NULL
);

ALTER TABLE LOC_PROPRIETARIO
       ADD CONSTRAINT PK_LOC_PROPRIETARIO PRIMARY KEY (CD_PROPRIETARIO);

ALTER TABLE LOC_PROPRIETARIO
       ADD CONSTRAINT CK_TP_PROPRIETARIO CHECK (TP_PROPRIETARIO IN ('F', 'J'));

CREATE TABLE LOC_RESERVA (
       DT_RESERVA           DATE 			NOT NULL,
       DT_RETIRADA          DATE 			NOT NULL,
       NR_PLACA             VARCHAR2(7) 	NOT NULL,
       NR_CARTAO_CREDITO    NUMBER(18) 		NULL,
       DT_INICIO_LOCACAO    DATE 			NOT NULL,
       DT_FIM_LOCACAO       DATE 			NOT NULL,
       CD_OPERADORA         NUMBER(8) 		NOT NULL,
       NM_CLIENTE           VARCHAR2(50) 	NOT NULL,
       HORA_RETIDADA        DATE 			NOT NULL,
       CIDADE_RETIRADA      VARCHAR2(20) 	NULL,
       STATUS               VARCHAR2(1) 	NOT NULL,
       CIDADE_DEVOLUCAO     VARCHAR2(20) 	NOT NULL,
       ENDERECO             VARCHAR2(50) 	NOT NULL,
       BAIRRO               VARCHAR2(40) 	NOT NULL,
       CIDADE               VARCHAR2(40) 	NOT NULL,
       ESTADO               VARCHAR2(30) 	NOT NULL,
       CEP                  NUMBER(8) 		NOT NULL,
       NR_HABILITACAO       NUMBER(18) 		NOT NULL,
       DT_NASCIMENTO        DATE		 	NOT NULL,
       TP_CLIENTE           VARCHAR2(1) 	NOT NULL,
       CPF_CNPJ             NUMBER(15) 		NOT NULL,
       CD_CIDADE            NUMBER(8) 		NULL,
       CD_AGENCIA           NUMBER(8) 		NULL,
       CD_ESTADO            VARCHAR2(2) 	NULL
);

ALTER TABLE LOC_RESERVA
       ADD CONSTRAINT PK_LOC_RESERVA PRIMARY KEY (NR_PLACA, DT_RESERVA);

ALTER TABLE LOC_RESERVA
       ADD CONSTRAINT CK_STATUS_RESERVA CHECK (STATUS IN ('A','C','E'));

ALTER TABLE LOC_RESERVA
       ADD CONSTRAINT CK_TP_CLIENTE_RESERVA CHECK (TP_CLIENTE IN ('F', 'J'));
	   
	   
CREATE TABLE LOC_VEICULO (
       NR_PLACA             VARCHAR2(7) 	NOT NULL,
       CD_PROPRIETARIO      NUMBER(10) 		NOT NULL,
       NR_CHASSIS           VARCHAR2(40) 	    NULL,
       STATUS               VARCHAR2(1) 	NOT NULL,
       TIPO_AUTOMOVEL       VARCHAR2(4) 	NULL,
       KM_ATUAL             NUMBER(10) 		NULL,
       COMBUSTIVEL          VARCHAR2(10) 	NULL,
       MODELO               VARCHAR2(30) 	NULL,
       COR                  VARCHAR2(15) 	NULL,
       CD_GRUPO             NUMBER(3) 		NOT NULL
);


ALTER TABLE LOC_VEICULO
       ADD CONSTRAINT PK_LOC_VEICULO PRIMARY KEY (NR_PLACA);

ALTER TABLE LOC_VEICULO
       ADD CONSTRAINT CK_STATUS_VEICULO CHECK (STATUS IN ('L', 'M', 'A','I'));
	   
	   
ALTER TABLE LOC_AGENCIA
       ADD CONSTRAINT FK_LOC_AGECID FOREIGN KEY (CD_CIDADE, CD_ESTADO)
                             REFERENCES LOC_CIDADE;


ALTER TABLE LOC_AGENCIA_BANCO
       ADD CONSTRAINT FK_LOC_AGEBAN FOREIGN KEY (CD_BANCO)
                             REFERENCES LOC_BANCO;


ALTER TABLE LOC_CIDADE
       ADD CONSTRAINT FK_LOC_CIDEST FOREIGN KEY (CD_ESTADO)
                             REFERENCES LOC_ESTADO;


ALTER TABLE LOC_CLI_FISICA
       ADD CONSTRAINT FK_LOC_FISCLI FOREIGN KEY (CD_CLIENTE)
                             REFERENCES LOC_CLIENTE;


ALTER TABLE LOC_CLI_JURIDICA
       ADD CONSTRAINT FK_LOC_JURCLI FOREIGN KEY (CD_CLIENTE)
                             REFERENCES LOC_CLIENTE;


ALTER TABLE LOC_COND_PARCELAS
       ADD CONSTRAINT FK_LOC_PARPAG FOREIGN KEY (CD_CONDICAO)
                             REFERENCES LOC_COND_PAGTO;

ALTER TABLE LOC_DDD_PREFIXO
       ADD CONSTRAINT FK_LOC_PREDDD FOREIGN KEY (CD_DDD, SEQ_DDD, ESTADO_DDD)
                             REFERENCES LOC_DDD;

ALTER TABLE LOC_DDD_PREFIXO
       ADD CONSTRAINT FK_LOC_PREPRE FOREIGN KEY (CD_PREFIXO)
                             REFERENCES LOC_PREFIXO;

ALTER TABLE LOC_DUPLICATA
       ADD CONSTRAINT FK_LOC_NF_DUPLOC FOREIGN KEY (NR_NOTA)
                             REFERENCES LOC_NF_LOCACAO;

ALTER TABLE LOC_ENDERECO_CLIENTE
       ADD CONSTRAINT FK_LOC_ENDCLI_CID FOREIGN KEY (CD_CIDADE, CD_ESTADO)
                             REFERENCES LOC_CIDADE;

ALTER TABLE LOC_ENDERECO_CLIENTE
       ADD CONSTRAINT FK_LOC_ENDCLI_CLI FOREIGN KEY (CD_CLIENTE)
                             REFERENCES LOC_CLIENTE;

ALTER TABLE LOC_ENDERECO_PROPRIETARIO
       ADD CONSTRAINT FK_LOC_END_PROCID FOREIGN KEY (CD_CIDADE, CD_ESTADO)
                             REFERENCES LOC_CIDADE;

ALTER TABLE LOC_ENDERECO_PROPRIETARIO
       ADD CONSTRAINT FK_LOC_END_PROP FOREIGN KEY (CD_PROPRIETARIO)
                             REFERENCES LOC_PROPRIETARIO;

ALTER TABLE LOC_FOTOS_VEICULO
       ADD CONSTRAINT FK_LOC_FOTVEI FOREIGN KEY (NR_PLACA)
                             REFERENCES LOC_VEICULO;

ALTER TABLE LOC_FUNCIONARIO
       ADD CONSTRAINT FK_LOC_FUNDEP FOREIGN KEY (CD_DEPTO)
                             REFERENCES LOC_DEPTO;

ALTER TABLE LOC_FUNCIONARIO
       ADD CONSTRAINT FK_LOC_FUNFUN FOREIGN KEY (CD_FUNC)
                             REFERENCES LOC_FUNCIONARIO;

ALTER TABLE LOC_IMPOSTOS
       ADD CONSTRAINT FK_LOC_IMPEST FOREIGN KEY (CD_ESTADO)
                             REFERENCES LOC_ESTADO;

ALTER TABLE LOC_IMPOSTOS
       ADD CONSTRAINT FK_LOC_IMPCID FOREIGN KEY (CD_CIDADE, CD_ESTADO)
                             REFERENCES LOC_CIDADE;

ALTER TABLE LOC_ITEM_LOCACAO
       ADD CONSTRAINT FK_LOC_ITLOC_PEDLOC FOREIGN KEY (NR_PEDIDO)
                             REFERENCES LOC_PEDIDO_LOCACAO;

ALTER TABLE LOC_ITEM_LOCACAO
       ADD CONSTRAINT FK_LOC_ITELOC_VEI FOREIGN KEY (NR_PLACA)
                             REFERENCES LOC_VEICULO;

ALTER TABLE LOC_MOVTO_COBRANCA
       ADD CONSTRAINT FK_LOC_MOVCOB_BANCO FOREIGN KEY (CD_BANCO)
                             REFERENCES LOC_BANCO;

ALTER TABLE LOC_MOVTO_COBRANCA
       ADD CONSTRAINT FK_LOC_MOVCOB_OPECART FOREIGN KEY (CD_OPERADORA)
                             REFERENCES LOC_OPERADORA_CARTAO;

ALTER TABLE LOC_MOVTO_COBRANCA
       ADD CONSTRAINT FK_LOC_MOVCOB_MOVTRAN FOREIGN KEY (CD_TRANSACAO)
                             REFERENCES LOC_MOVTO_TRANSACAO;

ALTER TABLE LOC_MOVTO_COBRANCA
       ADD CONSTRAINT FK_LOC_MOVCOB_LOCDUP FOREIGN KEY (NR_NOTA, CD_DUPLICATA)
                             REFERENCES LOC_DUPLICATA;

ALTER TABLE LOC_MOVTO_COMISSAO
       ADD CONSTRAINT FK_LOC_MOVCOM_LOCFUN FOREIGN KEY (CD_FUNC)
                             REFERENCES LOC_FUNCIONARIO;

ALTER TABLE LOC_MOVTO_COMISSAO
       ADD CONSTRAINT FK_LOC_MOVCOM_MOVCOB FOREIGN KEY (CD_MOVTO, NR_NOTA, CD_DUPLICATA)
                             REFERENCES LOC_MOVTO_COBRANCA;

ALTER TABLE LOC_NF_LOCACAO
       ADD CONSTRAINT FK_LOC_NFLOC_LOCCFO FOREIGN KEY (CFOP)
                             REFERENCES LOC_CFO;

ALTER TABLE LOC_NF_LOCACAO
       ADD CONSTRAINT FK_LOC_NFLOC_CONPAG FOREIGN KEY (CD_CONDICAO)
                             REFERENCES LOC_COND_PAGTO;

ALTER TABLE LOC_NF_LOCACAO
       ADD CONSTRAINT FK_LOC_NFLOC_PEDLOC FOREIGN KEY (NR_PEDIDO)
                             REFERENCES LOC_PEDIDO_LOCACAO;

ALTER TABLE LOC_NF_LOCACAO_ITEM
       ADD CONSTRAINT FK_LOC_NF_LOCITEM_LOCVEI FOREIGN KEY (NR_PLACA)
                             REFERENCES LOC_VEICULO;

ALTER TABLE LOC_NF_LOCACAO_ITEM
       ADD CONSTRAINT FK_LOC_NFLOC_ITEM_NFLOC FOREIGN KEY (NR_NOTA)
                             REFERENCES LOC_NF_LOCACAO;

ALTER TABLE LOC_OPERADORA_DDD
       ADD CONSTRAINT FK_LOC_OPEDDD_LOCDDD FOREIGN KEY (cd_ddd, seq_ddd, estado_ddd)
                             REFERENCES LOC_DDD;

ALTER TABLE LOC_OPERADORA_DDD
       ADD CONSTRAINT FK_LOC_OPEDDD_LOCOPE FOREIGN KEY (CD_OPERADORA)
                             REFERENCES LOC_OPERADORA;

ALTER TABLE LOC_PEDIDO_LOCACAO
       ADD CONSTRAINT FK_LOC_PEDLOC_LOCAGE FOREIGN KEY (CD_CIDADE, CD_AGENCIA, CD_ESTADO)
                             REFERENCES LOC_AGENCIA;

ALTER TABLE LOC_PEDIDO_LOCACAO
       ADD CONSTRAINT FK_LOC_PEDLOC_LOCFUN FOREIGN KEY (CD_FUNC)
                             REFERENCES LOC_FUNCIONARIO;

ALTER TABLE LOC_PEDIDO_LOCACAO
       ADD CONSTRAINT FK_LOC_PEDLOC_LOCCLI FOREIGN KEY (CD_CLIENTE)
                             REFERENCES LOC_CLIENTE;

ALTER TABLE LOC_RESERVA
       ADD CONSTRAINT FK_LOC_RES_LOCAGE FOREIGN KEY (CD_CIDADE, CD_AGENCIA, CD_ESTADO)
                             REFERENCES LOC_AGENCIA;

ALTER TABLE LOC_RESERVA
       ADD CONSTRAINT FK_LOC_RES_LOCOPE FOREIGN KEY (CD_OPERADORA)
                             REFERENCES LOC_OPERADORA;

ALTER TABLE LOC_RESERVA
       ADD CONSTRAINT FK_LOC_RES_LOCVEI FOREIGN KEY (NR_PLACA)
                             REFERENCES LOC_VEICULO;

ALTER TABLE LOC_VEICULO
       ADD CONSTRAINT FK_LOCVEI_LOCPRO FOREIGN KEY (CD_PROPRIETARIO)
                             REFERENCES LOC_PROPRIETARIO;

ALTER TABLE LOC_VEICULO
       ADD CONSTRAINT FK_LOCVEI_LOCGRU FOREIGN KEY (CD_GRUPO)
                             REFERENCES LOC_GRUPO;

CREATE SEQUENCE SEQ_LOC_MOVTO_TRANSACAO
 INCREMENT BY 1
 START WITH 0
 MAXVALUE 99999999999
 MINVALUE 0
 NOCYCLE
 NOCACHE
/

CREATE SEQUENCE SEQ_LOC_DDD
 INCREMENT BY 1
 START WITH 0
 MAXVALUE 99999999999
 MINVALUE 0
 NOCYCLE
 NOCACHE
/

CREATE SEQUENCE SEQ_LOC_CLI
 INCREMENT BY 1
 START WITH 0
 MAXVALUE 99999999999
 MINVALUE 0
 NOCYCLE
 NOCACHE
/

CREATE SEQUENCE SEQ_LOC_PEDIDO_LOCACAO
 INCREMENT BY 1
 START WITH 0
 MAXVALUE 99999999999
 MINVALUE 0
 NOCYCLE
 NOCACHE
/
